// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfc0fdpwYAie6CRK0iLrGrgsPWRjDg7Fw',
    appId: '1:182018769663:web:931daad006eb9ac1aa02ca',
    messagingSenderId: '182018769663',
    projectId: 'sahlschoolapp',
    authDomain: 'sahlschoolapp.firebaseapp.com',
    storageBucket: 'sahlschoolapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDciyilmb7bNn-jvk77xbZqLIJI-dvd638',
    appId: '1:182018769663:android:b44a1634ec9792aeaa02ca',
    messagingSenderId: '182018769663',
    projectId: 'sahlschoolapp',
    storageBucket: 'sahlschoolapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHfeSPTg0VToWVhsK6vM0VWoYIFHTdg_Q',
    appId: '1:182018769663:ios:17100c2d98dd2e37aa02ca',
    messagingSenderId: '182018769663',
    projectId: 'sahlschoolapp',
    storageBucket: 'sahlschoolapp.appspot.com',
    iosBundleId: 'com.sahl.sahlSchoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHfeSPTg0VToWVhsK6vM0VWoYIFHTdg_Q',
    appId: '1:182018769663:ios:4a6e9f8f1b07dee6aa02ca',
    messagingSenderId: '182018769663',
    projectId: 'sahlschoolapp',
    storageBucket: 'sahlschoolapp.appspot.com',
    iosBundleId: 'com.sahl.sahlSchoolApp.RunnerTests',
  );
}
